informacao = input("Digite uma informação: ")
print(f"O tipo primitivo dessa informação é: {type(informacao)}")
print(f"É alfanumérica? {informacao.isalnum()}")
print(f"É alfabética? {informacao.isalpha()}")
print(f"É ASCII? {informacao.isascii()}")
print(f"É decimal? {informacao.isdecimal()}")
print(f"É dígito? {informacao.isdigit()}")
print(f"É um identificador? {informacao.isidentifier()}")
print(f"Está em letras minúsculas? {informacao.islower()}")
print(f"É numérica? {informacao.isnumeric()}")
print(f"É imprimível? {informacao.isprintable()}")
print(f"Contém apenas espaços? {informacao.isspace()}")
print(f"Está em formato de título? {informacao.istitle()}")
print(f"Está em letras maiúsculas? {informacao.isupper()}")